algoritmo "ordemCrescenteEDecrescente"

var
valorX, valorY: inteiro
inicio

valorX <- 0
valorY <- 1

enquanto (valorX <> valorY) faca
   escreval("Digite o valor de X: ")
   leia(valorX)

   escreval("Digite o valor de Y: ")
   leia(valorY)


   se (valorX > valorY) e (valorX <> valorY) entao
      escreval("Valor digitado em ordem decrescente")
   senao
      se (valorX < valor Y)
         escreval("Valor digitado em ordem crescente")
      fimse
   fimse

fimenquanto

fimalgoritmo
